spring:
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  datasource:
    url: jdbc:mysql://47.92.196.104:3306/museum?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Qq1234!@#$
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 47.92.196.104 # Redis的服务地址
    port: 6380 # Redis的服务端口
    password:
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲链接
    timeout: 1200 # 连接池的超时时间（毫秒）

server:
  port: 8099

logging:
  level:
    #learning: debug
    root: INFO
    com.management.dao: trace
  pattern:
    console: '%p%m%n'