spring:
  datasource:
    url: jdbc:mysql://47.92.196.104:3306/museum?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Qq1234!@#$
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8099

logging:
  level:
    #learning: debug
    root: INFO
    com.management.dao: trace
  pattern:
    console: '%p%m%n'